name: Deploy Docs

on:
    push:
        branches: [master]

jobs:
    build:
        name: Deploy to GitHub Pages
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 'lts/*'
                  cache: 'yarn'

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Generate API documentation
              run: yarn docs

            - name: Deploy to GitHub Pages
              uses: crazy-max/ghaction-github-pages@v3
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  jekyll: false
                  build_dir: docs
                  target_branch: gh-pages
